<?xml version="1.0"?>
<!DOCTYPE RomBuildSet  [	
  <!ELEMENT RomBuildSet (Rom+)>
  <!ATTLIST RomBuildSet name CDATA #REQUIRED
                        revision CDATA #REQUIRED
  >
    
  <!ELEMENT Rom (InFile+,Macro*,ImageFile,XMLFile)>
  <!ATTLIST Rom name CDATA #REQUIRED
		TargetBoard CDATA #REQUIRED
  >  
  
  <!ELEMENT InFile EMPTY>  
  <!ATTLIST InFile name CDATA #REQUIRED>
	
  <!ELEMENT XMLFile EMPTY>  
  <!ATTLIST XMLFile name CDATA #REQUIRED>
    
  <!ELEMENT Macro EMPTY>  
  <!ATTLIST Macro name CDATA #REQUIRED
		value CDATA #IMPLIED
  >

  <!ELEMENT ImageFile EMPTY>
  <!ATTLIST ImageFile name CDATA #REQUIRED>
]>
<RomBuildSet name="RomSet" revision="1">
	
	<Rom name="GTC Mature H4" TargetBoard="H4hrp">
		<InFile name="GTC_Mature_H4"/>
		<ImageFile name="GTC_Mature_H4HRP.IMG"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC Mature H6" TargetBoard="H6">
		<InFile name="GTC_Mature_H6"/>
		<ImageFile name="GTC_Mature_H6HRP.IMG"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC Minimal H6" TargetBoard="H6">
		<InFile name="GTC_Minimal_H6"/>
		<ImageFile name="GTC_Minimal_H6HRP.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC MMC H4" TargetBoard="H4hrp">
		<InFile name="GTC_MMC_H4"/>
		<ImageFile name="GTC_MMC_H4HRP.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC Standard H4" TargetBoard="H4hrp">
		<InFile name="GTC_Standard_H4"/>
		<ImageFile name="GTC_Standard_H4HRP.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC Standard H6" TargetBoard="H6">
		<InFile name="GTC_Standard_H6"/>
		<ImageFile name="GTC_Standard_H6HRP.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC Standard NE1" TargetBoard="NE1">
		<InFile name="GTC_Standard_NE1"/>
		<ImageFile name="GTC_Standard_NaviE1.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
	<Rom name="GTC Standard NE1S" TargetBoard="NE1S">
		<InFile name="GTC_Standard_NE1S"/>
		<ImageFile name="GTC_Standard_NaviE1S.img"/>
		<XMLFile flag="-fm=" name="featuredatabase.XML"/>
	</Rom>
</RomBuildSet>