=== SymbianSource/oss.FCL.sf.os.deviceplatformrelease/symbianosbld/cedarutils/schedule12.dtd
<!ELEMENT Schedule12 (
	(CS|CR|OS|OR|REF|TEST|ISC)+,
	footnote*
	)
>
<!ATTLIST Schedule12
	Release_type CDATA #REQUIRED
	OS_version CDATA #REQUIRED
	DocVersion CDATA #REQUIRED
	Status CDATA #REQUIRED
	Schema CDATA #REQUIRED
>

<!ELEMENT CS (system_model*)>
<!ATTLIST CS
	name CDATA #REQUIRED
	draft (Y|N) "N"
>
<!ELEMENT CR (system_model*)>
<!ATTLIST CR
	name CDATA #REQUIRED
	draft (Y|N) "N"
>
<!ELEMENT OS (system_model*)>
<!ATTLIST OS
	name CDATA #REQUIRED
	draft (Y|N) "N"
>
<!ELEMENT OR (system_model*)>
<!ATTLIST OR
	name CDATA #REQUIRED
	draft (Y|N) "N"
>
<!ELEMENT REF (system_model*)>
<!ATTLIST REF
	name CDATA #REQUIRED
	more CDATA #IMPLIED
>
<!ELEMENT TEST (system_model*)>
<!ATTLIST TEST
	name CDATA #REQUIRED
	more CDATA #IMPLIED
>
<!ELEMENT ISC (system_model*)>
<!ATTLIST ISC
	name CDATA #REQUIRED
>

<!ELEMENT system_model EMPTY>
<!ATTLIST system_model
	entry CDATA #REQUIRED
>

<!ELEMENT footnote ANY>

=== SymbianSource/oss.FCL.sf.os.deviceplatformrelease/symbianosbld/cedarutils/Symbian_OS_vFuture_Schedule12.xml
<!DOCTYPE Schedule12 PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "schedule12.dtd">
<?xml-stylesheet type="text/xsl" href="schedule12.xsl" ?>

<Schedule12 Schema="2.0.0" 
	Status="DRAFT" 
	OS_version="tb101sf" Release_type="Update" 
	DocVersion="$Change: 1762010 $ $DateTime: 2010/02/12 16:02:11 $ $Id: //SSS/release/sf/tb92/os/deviceplatformrelease/symbianosbld/cedarutils/Symbian_OS_vFuture_Schedule12.xml#41 $" >
<OR name="Alarm Server">
	Maintains a queue of all system-wide alarms and provides APIs to manage alarms
	<system_model entry="Alarm Server"/>
</OR>
<OR name="Application Launch Services">
	System Starter, launches ROM-based servers that need to be
	started at device boot, depending on start-up mode.	
	<system_model entry="System State Management"/>
	<system_model entry="After Market Application Starter"/>
	<system_model entry="Application Launch Plugins"/>
</OR>
<OS name="Authentication Services" draft="Y">
    Server which allows clients to request that the phone holder authenticates themselves to the phone.
    <system_model entry="Authentication Server"/>
</OS>

<CS name="System State Management">
	Manages changes to device states, including start-up and shutdown, and changes to system wide properties (using policy plug-ins and command lists)
	<system_model entry="System State Manager"/>
</CS>
<OR name="System Health Management">
	Manages the system health, including the monitoring of critical processes and their re-launch if they fail
	<system_model entry="System Health Manager"/>
</OR>
<CR name="System State Management Plugins">
	Provide common policy plugins and adaptation plugins for System State Management Architecture
	<system_model entry="System State Plugins"/>
</CR>
<CS name="Application Utilities">
	Assorted basic utilities available to frameworks, services, and applications. 
	System utilities (BAFL) including resource file interface and clipboard, system sounds, 
	command-line parsing, descriptor arrays, resource file handling. 
	Used by higher level frameworks and services and available directly to applications.
	<system_model entry="Application Utilities"/>
</CS>
<CS name="Authorisation Services">
	Authorisation services, including the User Prompt Service (UPS) that allows system servers to generate prompts asking the user to authorise or deny a request from a client application.	
	<system_model entry="User Prompt Service"/>
</CS>
<OR name="User Prompt Utils">
	Utility library for use by service providers writing policy plug-ins for the UPS
	<system_model entry="User Prompt Utils"/>
</OR>
<OS name="BIO Messaging">
	Smart messaging framework and support. 
	In the System Model this is Bio Messaging Framework 
	and Bio Messaging Parsers.
	<system_model entry="BIO Messaging Framework"/>
	</OS>
<OS name="Bluetooth">
	Bluetooth connection and service manager and Bluetooth protocol stack. 
	System Model names are Bluetooth Manager, Bluetooth SDP and Bluetooth Stack PRT.
	<system_model entry="Bluetooth AVRCP"/>
	<system_model entry="Bluetooth PBAP"/>
	<system_model entry="Bluetooth Manager"/>
	<system_model entry="Bluetooth SDP"/>
	<system_model entry="Bluetooth Stack"/>
	<system_model entry="Remote Control Framework"/>
	<system_model entry="Bluetooth PAN Profile"/>
	<system_model entry="Bluetooth HCI Framework 2"/>
	<system_model entry="Bluetooth Logging Engine"/>
	<system_model entry="Bluetooth Notifiers Support"/>
	<system_model entry="Bluetooth Config"/>
	<system_model entry="Bluetooth GAVDP"/>
	<system_model entry="Bluetooth ROM"/>
	<system_model entry="Bluetooth Client Library"/>
	<system_model entry="Bluetooth Build Utilities"/>
	<system_model entry="Bluetooth HCI Extension Interface"/>
</OS>
<OR name="Content Handling">
	SMIL Rich Media Parser
	<system_model entry="SMIL Parser"/>
</OR>
<OR name="C Standard Library">
	C standard library for Symbian OS
	<system_model entry="C Standard Library"/>
</OR>
<OS name="Calendar Engine">
	Engine implementation for calendar application. 
	This is called Calendar in the System Model.
	<system_model entry="Calendar"/>
</OS>
<CR name="Client Provisioning Framework">
	OMA CP 1.1 compliant protocol implementation.
	Supports provisioning via WAP Push, Email, OBEX, Removable Media and the SIM.
	<system_model entry="Client Provisioning Framework"/>
</CR>
<CS name="Central Repository">
	Central setting database
	<system_model entry="Central Repository"/>
</CS>
<OR name="Certificate and Key Management">
	Certificate and key management framework and APIs
	<system_model entry="Certificate and Key Management"/>
	<system_model entry="Root Certificates"/>
	<system_model entry="File-based Certificate and Key Stores"/>
</OR>
<OS name="Security and Data Privacy Tools">
	A collection of PC-side tools and libraries for use with Security and Data Privacy
	<system_model entry="Security Tools"/>
</OS>
<CR name="Character Encoding Conversion" draft="Y">
	Character set converters. This includes the Character Encoding Conversion Framework. 
	<system_model entry="Character Encoding and Conversion Framework"/>
</CR>
<OR name="Character Encoding Conversion Plugins" draft="Y">
	Character set conversion plug-ins. This includes the Character Encoding Conversion Plug-ins. 
	<system_model entry="Character Encoding and Conversion Plugins"/>
</OR>
<OR name="Client Provisioning Adaptors">
	Supplies provisioning of network access points, WAP proxies, MMS, 
	OMA DS and OMA DM accounts, POP, IMAP and SMTP email accounts 
	and browser bookmarks.
	<system_model entry="Client Provisioning Adaptors"/>
	<system_model entry="Client Provisioning Adaptors Config"/>
	<system_model entry="Client Provisioning Framework Config"/>	
</OR>
<OR name="Device Management Configuration">
	Configuration settings for Device Management.
	<system_model entry="Device Management Adaptors Config"/>
	<system_model entry="Device Management Framework Config"/>
</OR>
<CS name="Comms Database">
	Networking and communications configuration information
	<system_model entry="Comms Database"/>
	<system_model entry="Comms Database Shim"/>
	<system_model entry="Prepare Default Comms Database"/>
	<system_model entry="Install Default Comms Database"/>
</CS>
<OR name="Comms File Logger">
	File logging engine used by comms framework and available to other components. 
	<system_model entry="File Logger"/>
	<system_model entry="Comms Debug Utility"/>
</OR>
<CS name="Comms Framework">
	Framework and utilities to support communications protocols and servers 
	including Comms Root Server, Comms Framework, Network Interface Manager and Comms Buffers.
	<system_model entry="Comms Root Server"/>
	<system_model entry="Comms Elements"/>
	<system_model entry="Comms Buffers"/>
	<system_model entry="Network Interface Manager"/>
	<system_model entry="Comms Root Server Config"/>
	<system_model entry="Comms User Prompt Manager"/>
</CS>
<CR name="Comms Plugin Module (CSY)">
	Comms Server CSY plugin providing serial port emulation over IR, USB, 
	Bluetooth and a virtual serial port.
	<system_model entry="Serial Port CSY"/>	
	<system_model entry="Bluetooth CSY"/>
	<system_model entry="MUX CSY"/>
</CR>
<OR name="Connection initiation">
	Network connection agents and agent plug-in interface providing connection to 
	circuit-switched and packet-switched networks. 
	Includes CSD AGT, PSD AGT and Network Controller.
	<system_model entry="PDP Layer"/>
	<system_model entry="QoS 3GPP CPR"/>
	<system_model entry="IP Transport Layer"/>
	<system_model entry="IP Network Layer"/>
	<system_model entry="QoS IP SCPR"/>
	<system_model entry="CSD AGT"/>
	<system_model entry="Network Controller"/>
	<system_model entry="NULL AGT"/>
	<system_model entry="PSD AGT"/>
	<system_model entry="TRP AGT"/>
	<system_model entry="Generic SCPR Parameters"/>
	<system_model entry="IP UPS Plugins"/>
	<system_model entry="Networking Dialog Stub"/>
	<system_model entry="Networking Dialog API"/>
</OR>
<OR name="Connectivity Device Side">
	Device side connectivity framework. This includes low level Device Connection Component, 
	Service Framework and Service Providers.
	<system_model entry="Active Backup Client"/>
	<system_model entry="Connectivity Services"/>
	<system_model entry="Connectivity Framework"/>
	<system_model entry="PLP Remote Link"/>
	<system_model entry="m-Router"/>
	<system_model entry="PLP Variant"/>
	<system_model entry="Backup Engine"/>
	<system_model entry="Backup Restore Notification"/>
</OR>
<OS name="Contacts Engine">
	Engine implementation for contacts application. 
	This is called Contacts Model in the System Model.
	<system_model entry="Contacts Model"/>
</OS>
<CS name="Content Access Framework v2 for DRM">
	Framework that enables DRM style content management. Note that this is the CAFv2 framework.
	<system_model entry="CAF Recogniser Config"/>
	<system_model entry="Content Access Framework for DRM"/>
</CS>
<OR name="CAF Streaming Support"> 
	Content Access Framework (CAF) support of streaming DRM solutions, such as DVB-H SPP and OMA DRM BCAST. 
	<system_model entry="CAF Streaming Support"/> 
</OR> 
<OS name="Cryptographic Token Framework">
	Framework supporting secure cryptographic tokens (e.g. smart cards)
	<system_model entry="Crypto Token Framework"/>
	<system_model entry="ASN PKCS"/>
</OS>
<OS name="Cryptography Library">
	Symmetric and asymmetric keys, hash algorithms, and pseudorandom number generators.
	Note this is export restricted
	<system_model entry="Weak Crypto SPI"/>
	<system_model entry="Strong Crypto SPI"/>
	<system_model entry="Security Utils"/>
	<system_model entry="Security Config"/>
</OS>
<OR name="Cryptography Plugins">
	Software plug-in for the Crypto SPI providing symmetric and asymmetric algorithms, hash algorithms, and pseudorandom number generators.
	Note this is export restricted
	<system_model entry="Crypto SPI Plugins"/>
</OR>
<OR name="Data Link Layer Protocols">
	Protocols utilities and interfaces for OSI Data Link Layer level protocols. 
	This includes a Link Layer Control group of components:
