<?xml version="1.0"?>
<!DOCTYPE RomBuildSet  [	
  <!ELEMENT RomBuildSet (Rom+)>
  <!ATTLIST RomBuildSet name CDATA #REQUIRED
                        revision CDATA #REQUIRED
  >
    
  <!ELEMENT Rom (InFile+,Macro*,ImageFile,XMLFile)>
  <!ATTLIST Rom name CDATA #REQUIRED
		TargetBoard CDATA #REQUIRED
  >  
  
  <!ELEMENT InFile EMPTY>  
  <!ATTLIST InFile name CDATA #REQUIRED>
	
  <!ELEMENT XMLFile EMPTY>  
  <!ATTLIST XMLFile name CDATA #REQUIRED>
    
  <!ELEMENT Macro EMPTY>  
  <!ATTLIST Macro name CDATA #REQUIRED
		value CDATA #IMPLIED
  >

  <!ELEMENT ImageFile EMPTY>
  <!ATTLIST ImageFile name CDATA #REQUIRED>
]>

<RomBuildSet name="RomSet" revision="1">
	<Rom name="H2 EABI" TargetBoard="H2">
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<ImageFile name="om_001.techview.IMG"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H2 EABI NAND" TargetBoard="H2">
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<Macro name="_NAND2" value=""/>
		<ImageFile name="om_001.techview.nand.IMG"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 EABI" TargetBoard="h4hrp">
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<ImageFile name="h4hrp_001.techview.IMG"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 EABI CDMA" TargetBoard="h4hrp">
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<Macro name="CDMA" value=""/>
		<ImageFile name="h4hrp_001.techview_cdma.IMG"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 EABI DevKit" TargetBoard="h4hrp">
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<InFile name="DevKit"/>	 			
		<ImageFile name="h4hrp_001.techview.devkit.img"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 Exclude Removable" TargetBoard="h4hrp">
		<InFile name="Techview_ExcludeRemovable"/>
		<InFile name="PlatSec"/>
		<ImageFile name="h4hrp_001.techview.ExcludeRemovable.img"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 EABI NAND" TargetBoard="h4hrp">
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<Macro name="_NAND2" value=""/>
		<Macro name="RVCT" value=""/>
		<Macro name="_EABI" value="ARMV5"/>
		<ImageFile name="h4hrp_001.techview.nand.IMG"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 Paged Rom" TargetBoard="h4hrp">
		<InFile name="Pagedrom"/>
		<InFile name="Techview"/>
		<InFile name="PlatSec"/>
		<Macro name="_NAND2" value=""/>
		<ImageFile name="h4hrp_001.techview.DemandPaging.img"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
	<Rom name="H4 TextShell Rom" TargetBoard="h4hrp">
		<InFile name="Textshell"/>
		<InFile name="PlatSec"/>
		<ImageFile name="h4hrp_001.textshell.img"/>
		<XMLFile name="featureUIDs.XML"/>
	</Rom>
</RomBuildSet>

